version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306  # Map container port 3306 to host port 3307
    environment:
      MYSQL_DATABASE: jon
      MYSQL_ROOT_PASSWORD: 1101
      MYSQL_ROOT_HOST: '%'
